[2025-02-23T04:33:03.340+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T04:33:03.381+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v1.first_task scheduled__2021-04-20T00:00:00+00:00 [queued]>
[2025-02-23T04:33:03.406+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v1.first_task scheduled__2021-04-20T00:00:00+00:00 [queued]>
[2025-02-23T04:33:03.409+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T04:33:03.567+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2021-04-20 00:00:00+00:00
[2025-02-23T04:33:03.584+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v1', 'first_task', 'scheduled__2021-04-20T00:00:00+00:00', '--job-id', '768', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpr9f7nvbd']
[2025-02-23T04:33:03.585+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3611) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T04:33:03.588+0000] {standard_task_runner.py:105} INFO - Job 768: Subtask first_task
[2025-02-23T04:33:03.589+0000] {standard_task_runner.py:72} INFO - Started process 3625 to run task
[2025-02-23T04:33:03.707+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v1.first_task scheduled__2021-04-20T00:00:00+00:00 [running]> on host f66dd6409c88
[2025-02-23T04:33:03.897+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vn5705j' AIRFLOW_CTX_DAG_ID='our_first_dag_v1' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2021-04-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-20T00:00:00+00:00'
[2025-02-23T04:33:03.901+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T04:33:03.942+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T04:33:03.944+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Hello World!' This is the first Task"]
[2025-02-23T04:33:03.984+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T04:33:03.988+0000] {subprocess.py:106} INFO - Hello World! This is the first Task
[2025-02-23T04:33:03.990+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T04:33:04.055+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T04:33:04.061+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v1, task_id=first_task, run_id=scheduled__2021-04-20T00:00:00+00:00, execution_date=20210420T000000, start_date=20250223T043303, end_date=20250223T043304
[2025-02-23T04:33:04.256+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T04:33:04.320+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-23T04:33:04.328+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
